# alacritty.toml

general.live_config_reload = true

[env]
TERM = "alacritty"

[window]
decorations     = "none"
dynamic_padding = false
dynamic_title   = true
opacity         = 0.89
startup_mode    = "Windowed"
title           = "terminal"

[window.dimensions]
columns = 90
lines   = 25

[window.padding]
x = 0
y = 6

[scrolling]
history = 10000

[font]
builtin_box_drawing = false
size                = 11

[font.bold]
family = "FiraCode NerdFont"
style  = "SemiBold"

[font.bold_italic]
family = "FiraCode NerdFont"
style  = "SemiBold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "FiraCode NerdFont"
style  = "Italic"

[font.normal]
family = "FiraCode NerdFont"
style  = "SemiBold"

[font.offset]
x = -1
y = 0

[colors.primary]
background = "#1d1d1d"
foreground = "#eceff4"

[colors.bright]
black   = "#60728a"
blue    = "#81a1c1"
cyan    = "#8fc6c5"
green   = "#b1c89d"
magenta = "#be9db8"
red     = "#c5727a"
white   = "#eceff4"
yellow  = "#efd49f"

[colors.cursor]
cursor = "#b0b8c6"
text   = "#1a1a1a"

[colors.footer_bar]
background = "#171825"
foreground = "#eeeeee"

[colors.hints.end]
background = "CellBackground"
foreground = "CellForeground"

[colors.hints.start]
background = "CellBackground"
foreground = "CellForeground"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.normal]
black   = "#2e3440"
blue    = "#5e81ac"
cyan    = "#8fbcbb"
green   = "#a3be8c"
magenta = "#b48ead"
red     = "#bf616a"
white   = "#e5e9f0"
yellow  = "#ebcb8b"

[colors.search.focused_match]
background = "CellBackground"
foreground = "#c0c8d8"

[colors.search.matches]
background = "CellBackground"
foreground = "#c0c8d8"

[colors.selection]
background = "#c0c8d8"
text       = "CellBackground"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text   = "CellBackground"

[bell]
animation = "EaseOutExpo"
color     = "#C0C5CE"
command   = "None"
duration  = 0

[selection]
save_to_clipboard     = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[cursor]
style = "Block"
unfocused_hollow = true
vi_mode_style    = "Block"

[[keyboard.bindings]]
action = "Paste"
key    = "V"
mods   = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key    = "C"
mods   = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollPageUp"
key    = "PageUp"
mods   = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key    = "PageDown"
mods   = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key    = "Home"
mods   = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key    = "End"
mods   = "Shift"

[mouse]
hide_when_typing = true

[debug]
highlight_damage   = false
log_level          = "Warn"
persistent_logging = false
print_events       = false
render_timer       = false
