typeset -A ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_STYLES[suffix-alias]=fg=white
ZSH_HIGHLIGHT_STYLES[precommand]=fg=white
ZSH_HIGHLIGHT_STYLES[arg0]=fg=white
ZSH_HIGHLIGHT_STYLES[unknown-token]=fg=#b74e58
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#60728a,bold,underline"
zle_highlight=('paste:none')

autoload -U compinit
zstyle ':completion*' menu select
zmodload zsh/complist
compinit
_comp_options+=(globdots)

bindkey "^[[1;5C" forward-word
bindkey "^[[1;5D" backward-word

# Edit command in vim
autoload edit-command-line; zle -N edit-command-line
bindkey '^e' edit-command-line

setopt correct
setopt nocheckjobs
setopt append_history 
setopt inc_append_history 
setopt share_history
setopt auto_menu 
setopt menu_complete
setopt autocd
setopt nobeep
setopt auto_param_slash
setopt globdots
unsetopt prompt_sp

# Keep autosuggestion history
setopt APPEND_HISTORY
setopt SHARE_HISTORY
HISTFILE=$HOME/.zhistory
SAVEHIST=1000
HISTSIZE=999
setopt HIST_EXPIRE_DUPS_FIRST
setopt EXTENDED_HISTORY

   export EDITOR='nvim'
   export VISUAL='nvim'
   alias v='nvim'
   alias sv='sudo -E nvim'
   alias tclock='tty-clock -s -c -C 4 -b -t'
   alias pipes.sh='pipes.sh -R -b -p 8 -r 3500'
   alias alarm='~/.local/bin/alarm/alarm.sh'

[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

source ~/powerlevel10k/powerlevel10k.zsh-theme
# Plugins Via Source
source /usr/share/zsh/plugins/zsh-auto-notify/auto-notify.plugin.zsh
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh
source /usr/share/zsh/plugins/zsh-you-should-use/zsh-you-should-use.plugin.zsh
source /usr/share/zsh/plugins/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh
source /usr/share/zsh/plugins/zsh-completions/zsh-completions.plugin.zsh
